### ISSUE TITLE
Missing range constraints for `TIMESTAMP_CELL` symbolic variable

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/kontrol#315] opened 2024-01-25 20:46 UTC
Kontrol uses the symbolic variable `TIMESTAMP_CELL` to represent the value `block.timestamp` in Solidity, but it doesn't introduce range constraints for this variable (`0 <=Int TIMESTAMP_CELL` and `TIMESTAMP_CELL <Int pow256`). This means, for example, that the following test will fail in Kontrol:
```
function testTimestamp() public {
    assertLe(block.timestamp, type(uint256).max);
}
```
It will also prevent expressions that use `TIMESTAMP_CELL` from simplifying. For example, `#asWord ( #range ( #padToWidth ( 32 , #asByteStack ( TIMESTAMP_CELL:Int ) ) , 0 , 32 ) )` should simplify to just `TIMESTAMP_CELL`, but only if its range is constrained.

**Comment by lucasmt** [comment] 2024-01-25 21:28
I'd be happy to submit a PR fixing this, but I don't actually know where these constraints get added

**Comment by anvacaru** [comment] 2024-01-30 13:03
Constraints like this are added in evm-semantics, in [`KEVM.add_invariant`](https://github.com/runtimeverification/evm-semantics/blob/9fd7bc1238949ff585416c59f16382bee64707e6/kevm-pyk/src/kevm_pyk/kevm.py#L246) method.

**Comment by anvacaru** [comment] 2024-01-31 06:28
Closing this as it is a duplicate of https://github.com/runtimeverification/evm-semantics/issues/2143.

**Closed by anvacaru** 2024-01-31 06:28 UTC
