### ISSUE TITLE
Downstream testing using engagement codebases

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#17] opened 2023-08-11 08:34 UTC
We should integrate proofs from previous and ongoing engagements into our CI, e.g., perform downstream testing using the corresponding repositories and run these tests, e.g., weekly. To be further discussed with @ehildenb and @JuanCoRo.

**Comment by JuanCoRo** [comment] 2023-09-26 14:06
My understanding of the roadmap for integrating engagement repos into Kontrol's CI is the following:
- Get automatic PRs for new Kontrol releases in engagements repos
- Set the CI of engagement repos so that new and existent proofs have to pass on the pegged Kontrol version
- Require for new releases of Kontrol that engagement repos will not break

So this issue would be the third item on the list, which should be done after the first two. @F-WRunTime could you check if I'm missing anything?
Currently, the first item is being implemented in the Solady repo.

**Comment by F-WRunTime** [comment] 2023-09-29 19:44
Here is an example of a downstream being started and run with a [new release of Kontrol ](https://github.com/runtimeverification/kontrol-solady/pull/4)

Failure is due to updates needing to be merged to the master branch in order for the proofs to be run properly. The CI However has been setup to properly be kicked off with new updates to Kontrol. 

Next effort is to create a feedback loop in the Upstream repositories to create new Major.Minor Versions based on the cumulative or subset of passing tests from engagement repositories. This should enable us to create "golden" releases that have passed our "regression" testing -- in our lifecycle it is our proofs using our kontrol tool. -- I think this should be tracked as a separate / new issue. Please assign to me.

**Comment by F-WRunTime** [comment] 2023-09-29 19:46
The template repository we should use to further test the CI setup is [here](https://github.com/runtimeverification/audit-kontrol-template)

Before closing this issue entirely. I would like to do a run through of using this template along with @JuanCoRo after any additional changes to the template are added to support a quick start-up of an engagement and allow a quick start to writing proofs and having tests run against them using the process of opening a PR in the engagement repository.

**Closed** 2024-03-14 15:39 UTC
Labels: enhancement
